import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2.55.0/+esm';

const supabase = createClient('https://pztlorpsjnvptgmckerp.supabase.co','sb_publishable_ZBH7xWrqHWen-le5GNmz6A_yiVPZ9B_');
const $ = s => document.querySelector(s); const content=$('#content');
const roleNames={teacher:'المعلم',secretary:'السكرتيرة',student:'الطالب',guardian:'ولي الأمر'};
let profile=null, currentPage='dashboard';

document.querySelectorAll('[data-auth-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-auth-tab]').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#loginForm').classList.toggle('hidden',b.dataset.authTab!=='login');$('#signupForm').classList.toggle('hidden',b.dataset.authTab!=='signup')});
$('#loginForm').onsubmit=async e=>{e.preventDefault();setAuthMsg('جارٍ تسجيل الدخول…');const {error}=await supabase.auth.signInWithPassword({email:$('#loginEmail').value,password:$('#loginPassword').value});if(error)setAuthMsg(arError(error.message));};
$('#signupForm').onsubmit=async e=>{e.preventDefault();setAuthMsg('جارٍ إنشاء الحساب…');const {error}=await supabase.auth.signUp({email:$('#signupEmail').value,password:$('#signupPassword').value,options:{data:{full_name:$('#signupName').value}}});setAuthMsg(error?arError(error.message):'تم إنشاء الحساب. افحص بريدك للتأكيد، ثم اطلب من المعلم تعيين الدور وربط الحساب.');};
$('#logoutBtn').onclick=()=>supabase.auth.signOut(); $('#menuBtn').onclick=()=>$('.sidebar').classList.toggle('open');
function setAuthMsg(t){$('#authMessage').textContent=t;$('#authMessage').classList.remove('hidden')}function arError(t){return t.includes('Invalid login')?'البريد الإلكتروني أو كلمة المرور غير صحيحة.':t}

supabase.auth.onAuthStateChange((_e,session)=>session?boot(session.user):showAuth());
async function boot(user){const {data,error}=await supabase.from('profiles').select('*').eq('id',user.id).single();if(error){setAuthMsg('تعذر تحميل صلاحيات الحساب.');return}profile=data;$('#authView').classList.add('hidden');$('#appView').classList.remove('hidden');$('#userName').textContent=profile.full_name||user.email;$('#userInitial').textContent=(profile.full_name||'م')[0];$('#userRole').textContent=roleNames[profile.role];buildNav();navigate('dashboard')}
function showAuth(){$('#appView').classList.add('hidden');$('#authView').classList.remove('hidden');profile=null}
const navByRole={teacher:[['dashboard','⌂','نظرة عامة'],['students','♙','الطلاب'],['attendance','✓','الحضور'],['grades','◇','الدرجات'],['payments','□','الاشتراكات والملزمة'],['expenses','↙','المصروفات'],['users','⚙','الحسابات']],secretary:[['dashboard','⌂','نظرة عامة'],['students','♙','الطلاب'],['attendance','✓','الحضور'],['grades','◇','الدرجات']],student:[['dashboard','⌂','ملخصي'],['my-attendance','✓','حضوري'],['my-grades','◇','درجاتي'],['my-payments','□','المدفوعات']],guardian:[['dashboard','⌂','ملخص الأبناء'],['my-attendance','✓','الحضور'],['my-grades','◇','الدرجات'],['my-payments','□','المدفوعات']]};
function buildNav(){const n=$('#nav');n.innerHTML=navByRole[profile.role].map(([id,ic,t])=>`<button data-page="${id}"><span>${ic}</span>${t}</button>`).join('');n.querySelectorAll('button').forEach(b=>b.onclick=()=>navigate(b.dataset.page))}
async function navigate(page){currentPage=page;document.querySelectorAll('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===page));$('.sidebar').classList.remove('open');const titles={dashboard:'نظرة عامة',students:'إدارة الطلاب',attendance:'الحضور والغياب',grades:'الاختبارات والدرجات',payments:'الاشتراكات ورسوم الملزمة',expenses:'مصروفات المعلم',users:'الحسابات والصلاحيات','my-attendance':'سجل الحضور','my-grades':'الدرجات والإنجاز','my-payments':'حالة المدفوعات'};$('#pageTitle').textContent=titles[page];content.innerHTML='<div class="empty">جارٍ تحميل البيانات…</div>';await ({dashboard,students,attendance,grades,payments,expenses,users,'my-attendance':familyAttendance,'my-grades':familyGrades,'my-payments':familyPayments}[page]||dashboard)()}
const count=async table=>(await supabase.from(table).select('*',{count:'exact',head:true})).count||0;
async function dashboard(){if(['student','guardian'].includes(profile.role))return familyDashboard();const [students,attendance,grades]=await Promise.all([count('students'),count('attendance'),count('grades')]);let financial='—';if(profile.role==='teacher'){const {data}=await supabase.from('payments').select('amount_paid');financial=(data||[]).reduce((s,x)=>s+Number(x.amount_paid),0).toLocaleString('ar-EG')+' ج.م'}content.innerHTML=`<section class="stats"><article class="stat"><span>إجمالي الطلاب</span><b>${students}</b><i>قاعدة الطلاب</i></article><article class="stat"><span>سجلات الحضور</span><b>${attendance}</b><i>متابعة مستمرة</i></article><article class="stat"><span>الدرجات المسجلة</span><b>${grades}</b><i>اختبارات قصيرة</i></article><article class="stat"><span>${profile.role==='teacher'?'إجمالي المحصل':'صلاحية الحساب'}</span><b style="font-size:22px">${profile.role==='teacher'?financial:'تشغيلية'}</b><i>${roleNames[profile.role]}</i></article></section><section class="grid-2"><div class="panel"><div class="panel-head"><h3>مركز الإدارة</h3></div><p class="muted">ابدأ بإضافة المواد والطلاب وربط كل طالب بالمادة، ثم سجّل الحضور والدرجات.</p><button class="primary" onclick="window.goPage('students')">إدارة الطلاب</button></div><div class="panel"><h3>خصوصية البيانات</h3><p class="muted">الصلاحيات مطبقة داخل قاعدة البيانات؛ إخفاء القوائم وحده ليس وسيلة الحماية.</p></div></section>`}
window.goPage=navigate;
async function students(){const [{data:students},{data:subjects}]=await Promise.all([supabase.from('students').select('*').order('created_at',{ascending:false}),supabase.from('subjects').select('*').order('name')]);content.innerHTML=`<section class="grid-2"><div class="panel"><div class="panel-head"><h3>الطلاب</h3><span>${students?.length||0} طالب</span></div>${table(students,['full_name','grade_level','phone','joined_on'],['الاسم','الصف','الهاتف','تاريخ الالتحاق'])}</div><div class="panel"><h3>إضافة طالب</h3><form id="studentForm" class="form-grid"><label>الاسم<input name="full_name" required></label><label>الصف<input name="grade_level" required></label><label>هاتف الطالب<input name="phone"></label><label>هاتف ولي الأمر<input name="parent_phone"></label><label class="wide">ملاحظات<textarea name="notes"></textarea></label><button class="primary wide">حفظ الطالب</button></form><hr><h3>إضافة مادة</h3><form id="subjectForm" class="form-grid"><label class="wide">اسم المادة<input name="name" required placeholder="علم النفس"></label><button class="primary wide">حفظ المادة</button></form><hr><h3>ربط طالب بمادة</h3><form id="enrollForm" class="form-grid"><label>الطالب<select name="student_id" required>${opts(students,'full_name')}</select></label><label>المادة<select name="subject_id" required>${opts(subjects,'name')}</select></label><label>الاشتراك الشهري<input type="number" name="monthly_fee" value="0" min="0"></label><label>رسوم الملزمة<input type="number" name="booklet_fee" value="0" min="0"></label><button class="primary wide">حفظ الربط</button></form></div></section>`;$('#studentForm').onsubmit=e=>submitForm(e,'students');$('#subjectForm').onsubmit=e=>submitForm(e,'subjects');$('#enrollForm').onsubmit=e=>submitForm(e,'enrollments')}
async function attendance(){const [{data},{data:enrollments}]=await Promise.all([supabase.from('attendance').select('*,enrollments(students(full_name),subjects(name))').order('attended_on',{ascending:false}),supabase.from('enrollments').select('id,students(full_name),subjects(name)').eq('active',true)]);const rows=data?.map(x=>({...x,student:x.enrollments?.students?.full_name,subject:x.enrollments?.subjects?.name}));const form=profile.role==='student'||profile.role==='guardian'?'':`<div class="panel"><h3>تسجيل حضور</h3><form id="attendanceForm" class="form-grid"><label class="wide">الطالب والمادة<select name="enrollment_id" required>${opts(enrollments,x=>x.students?.full_name+' — '+x.subjects?.name)}</select></label><label>التاريخ<input type="date" name="attended_on" required></label><label>الحالة<select name="status"><option value="present">حاضر</option><option value="absent">غائب</option><option value="late">متأخر</option><option value="excused">بعذر</option></select></label><button class="primary wide">حفظ</button></form></div>`;content.innerHTML=`<section class="grid-2"><div class="panel">${table(rows,['student','subject','attended_on','status'],['الطالب','المادة','التاريخ','الحالة'])}</div>${form}</section>`;if($('#attendanceForm'))$('#attendanceForm').onsubmit=e=>submitForm(e,'attendance',null,{recorded_by:profile.id})}
async function grades(){const [{data},{data:students},{data:exams},{data:subjects}]=await Promise.all([supabase.from('grades').select('*,students(full_name),exams(title,max_score)').order('created_at',{ascending:false}),supabase.from('students').select('id,full_name'),supabase.from('exams').select('id,title,max_score'),supabase.from('subjects').select('id,name')]);const rows=data?.map(x=>({...x,student:x.students?.full_name,exam:x.exams?.title,result:`${x.score} / ${x.exams?.max_score}`}));const form=['teacher','secretary'].includes(profile.role)?`<div class="panel"><h3>إنشاء اختبار</h3><form id="examForm" class="form-grid"><label>المادة<select name="subject_id">${opts(subjects,'name')}</select></label><label>العنوان<input name="title" required></label><label>التاريخ<input type="date" name="exam_date" required></label><label>الدرجة النهائية<input type="number" name="max_score" min="1" required></label><button class="primary wide">حفظ الاختبار</button></form><hr><h3>إضافة درجة</h3><form id="gradeForm" class="form-grid"><label>الطالب<select name="student_id">${opts(students,'full_name')}</select></label><label>الاختبار<select name="exam_id">${opts(exams,x=>x.title+' ('+x.max_score+')')}</select></label><label class="wide">الدرجة<input type="number" step=".01" name="score" min="0" required></label><button class="primary wide">حفظ الدرجة</button></form></div>`:'';content.innerHTML=`<section class="grid-2"><div class="panel">${table(rows,['student','exam','result'],['الطالب','الاختبار','النتيجة'])}</div>${form}</section>`;if($('#examForm'))$('#examForm').onsubmit=e=>submitForm(e,'exams',null,{created_by:profile.id});if($('#gradeForm'))$('#gradeForm').onsubmit=e=>submitForm(e,'grades',null,{recorded_by:profile.id})}
async function payments(){const [{data},{data:enrollments}]=await Promise.all([supabase.from('payments').select('*,enrollments(students(full_name),subjects(name))').order('billing_month',{ascending:false}),supabase.from('enrollments').select('id,students(full_name),subjects(name)').eq('active',true)]);const rows=data?.map(x=>({...x,student:x.enrollments?.students?.full_name,type:x.payment_type==='subscription'?'اشتراك':'ملزمة',money:`${x.amount_paid} / ${x.amount_due}`}));const form=profile.role==='teacher'?`<div class="panel"><h3>تسجيل استحقاق أو دفعة</h3><form id="paymentForm" class="form-grid"><label class="wide">الطالب والمادة<select name="enrollment_id">${opts(enrollments,x=>x.students?.full_name+' — '+x.subjects?.name)}</select></label><label>البند<select name="payment_type"><option value="subscription">اشتراك</option><option value="booklet">ملزمة</option></select></label><label>شهر الاستحقاق<input type="date" name="billing_month" required></label><label>المطلوب<input type="number" name="amount_due" min="0" required></label><label>المدفوع<input type="number" name="amount_paid" min="0" value="0"></label><label>الحالة<select name="status"><option value="unpaid">غير مدفوع</option><option value="partial">جزئي</option><option value="paid">مدفوع</option></select></label><label>تاريخ الدفع<input type="date" name="paid_on"></label><button class="primary wide">حفظ</button></form></div>`:'';content.innerHTML=`<section class="grid-2"><div class="panel">${table(rows,['student','type','billing_month','money','status'],['الطالب','البند','الشهر','المدفوع/المطلوب','الحالة'])}</div>${form}</section>`;if($('#paymentForm'))$('#paymentForm').onsubmit=e=>submitForm(e,'payments',null,{recorded_by:profile.id})}
async function expenses(){const {data}=await supabase.from('teacher_expenses').select('*').order('expense_date',{ascending:false});content.innerHTML=`<section class="grid-2"><div class="panel">${table(data,['expense_date','category','description','amount'],['التاريخ','التصنيف','البيان','المبلغ'])}</div><div class="panel"><h3>إضافة مصروف</h3><form id="expenseForm" class="form-grid"><label>التاريخ<input type="date" name="expense_date" required></label><label>التصنيف<input name="category" required></label><label class="wide">البيان<input name="description" required></label><label class="wide">المبلغ<input type="number" step="0.01" name="amount" required></label><button class="primary wide">حفظ</button></form></div></section>`;$('#expenseForm').onsubmit=e=>submitForm(e,'teacher_expenses',null,{created_by:profile.id})}
async function users(){const [{data},{data:students}]=await Promise.all([supabase.from('profiles').select('*').order('created_at',{ascending:false}),supabase.from('students').select('id,full_name')]);content.innerHTML=`<section class="grid-2"><div class="panel">${table(data?.map(x=>({...x,role_ar:roleNames[x.role]})),['full_name','phone','role_ar','active'],['الاسم','الهاتف','الصلاحية','نشط'])}</div><div class="panel"><h3>تعديل صلاحية حساب</h3><form id="roleForm" class="form-grid"><label class="wide">الحساب<select name="id">${opts(data,x=>x.full_name+' — '+roleNames[x.role])}</select></label><label class="wide">الدور<select name="role"><option value="teacher">معلم</option><option value="secretary">سكرتيرة</option><option value="student">طالب</option><option value="guardian">ولي أمر</option></select></label><button class="primary wide">تحديث الصلاحية</button></form><hr><h3>ربط حساب طالب بسجله</h3><form id="linkStudentForm" class="form-grid"><label>الحساب<select name="user_id">${opts(data?.filter(x=>x.role==='student'),'full_name')}</select></label><label>الطالب<select name="id">${opts(students,'full_name')}</select></label><button class="primary wide">حفظ الربط</button></form></div></section>`;$('#roleForm').onsubmit=async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target));const {error}=await supabase.from('profiles').update({role:f.role}).eq('id',f.id);error?toast(error.message):(toast('تم تحديث الصلاحية'),navigate('users'))};$('#linkStudentForm').onsubmit=async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target));const {error}=await supabase.from('students').update({user_id:f.user_id}).eq('id',f.id);error?toast(error.message):(toast('تم ربط الحساب'),navigate('users'))}}
async function familyDashboard(){const {data:s}=await supabase.from('students').select('*');const {data:a}=await supabase.from('attendance').select('status');const {data:g}=await supabase.from('grades').select('score,exams(max_score)');const total=a?.length||0,present=a?.filter(x=>x.status==='present').length||0,avg=g?.length?Math.round(g.reduce((z,x)=>z+(Number(x.score)/Number(x.exams?.max_score||1))*100,0)/g.length):0;content.innerHTML=`<section class="stats"><article class="stat"><span>الطلاب المرتبطون</span><b>${s?.length||0}</b></article><article class="stat"><span>نسبة الحضور</span><b>${total?Math.round(present/total*100):0}%</b></article><article class="stat"><span>متوسط الإنجاز</span><b>${avg}%</b></article><article class="stat"><span>سجلات المتابعة</span><b>${total}</b></article></section><section class="panel" style="margin-top:18px"><h3>التقدم الدراسي</h3><p class="muted">متوسط الدرجات المحققة</p><div class="progress"><span style="width:${avg}%"></span></div></section>`}
async function familyAttendance(){return attendance()}async function familyGrades(){return grades()}async function familyPayments(){return payments()}
function panelTable(title,data,fields,heads){return `<section class="panel"><div class="panel-head"><h3>${title}</h3><span>${data?.length||0} سجل</span></div>${table(data,fields,heads)}</section>`}
function opts(data,label){return '<option value="">اختر…</option>'+((data||[]).map(x=>`<option value="${x.id}">${typeof label==='function'?label(x):x[label]}</option>`).join(''))}
function table(data,fields,heads){if(!data?.length)return '<div class="empty">لا توجد بيانات حتى الآن</div>';return `<div class="table-wrap"><table><thead><tr>${heads.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${data.map(r=>`<tr>${fields.map(f=>`<td>${fmt(r[f])}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`}
function fmt(v){if(v===true)return '<span class="badge green">نعم</span>';if(v===false)return '<span class="badge red">لا</span>';const m={present:'حاضر',absent:'غائب',late:'متأخر',excused:'بعذر',paid:'مدفوع',unpaid:'غير مدفوع',partial:'جزئي'};return m[v]||v||'—'}
async function submitForm(e,tableName,_reload,extra={}){e.preventDefault();const btn=e.submitter;btn.disabled=true;const payload=Object.fromEntries(new FormData(e.target));Object.keys(payload).forEach(k=>{if(payload[k]==='')payload[k]=null});const {error}=await supabase.from(tableName).insert({...payload,...extra});btn.disabled=false;if(error)return toast(error.message);toast('تم الحفظ بنجاح');navigate(currentPage)}
function toast(t){const el=$('#toast');el.textContent=t;el.classList.remove('hidden');setTimeout(()=>el.classList.add('hidden'),3200)}
